import {
  getDefaultLayoutForStation,
  getDefaultMapLayout,
  getDefaultMapZoneLabels,
} from "./mapConstants";
import type { AppData, Station } from "./types";
import { DEFAULT_SECTION_TIMING } from "./types";

function seedStation(
  partial: Omit<Station, "map_x" | "map_y" | "map_width" | "map_height">
): Station {
  return { ...partial, ...getDefaultLayoutForStation(partial as Station) };
}

export const DEFAULT_DATA: AppData = {
  users: [
    {
      id: "user-admin",
      username: "martin long",
      password: "doh",
      name: "Martin Long",
      role: "admin",
    },
    {
      id: "user-eduardo",
      username: "eduardo ramirez",
      password: "doh",
      name: "Eduardo Ramirez",
      role: "user",
    },
  ],
  stations: [
    seedStation({
      id: "station-kitchen",
      name: "Kitchen Line",
      slug: "kitchen-line",
      color: "#ef4444",
    }),
    seedStation({
      id: "station-prep",
      name: "Prep Area",
      slug: "prep-area",
      color: "#f59e0b",
    }),
    seedStation({
      id: "station-dish",
      name: "Dishwashing",
      slug: "dishwashing",
      color: "#3b82f6",
    }),
    seedStation({
      id: "station-storage",
      name: "Storage",
      slug: "storage",
      color: "#10b981",
    }),
  ],
  sections: [
    {
      id: "section-kitchen-opening",
      station_id: "station-kitchen",
      name: "Pre-Service",
      sort_order: 1,
      time: "06:00",
      recurrence: "daily_once",
      interval_minutes: null,
      due_window_minutes: 60,
    },
    {
      id: "section-kitchen-mid",
      station_id: "station-kitchen",
      name: "Service Hours",
      sort_order: 2,
      ...DEFAULT_SECTION_TIMING,
    },
    {
      id: "section-kitchen-temp",
      station_id: "station-kitchen",
      name: "Temperature Monitoring",
      sort_order: 3,
      recurrence: "interval",
      interval_minutes: 120,
      due_window_minutes: 30,
    },
    {
      id: "section-kitchen-closing",
      station_id: "station-kitchen",
      name: "End of Day",
      sort_order: 4,
      time: "22:00",
      recurrence: "daily_once",
      interval_minutes: null,
      due_window_minutes: 90,
    },
    {
      id: "section-prep-pre-open",
      station_id: "station-prep",
      name: "Pre-Service",
      sort_order: 1,
      time: "06:30",
      recurrence: "daily_once",
      interval_minutes: null,
      due_window_minutes: 60,
    },
    {
      id: "section-prep-mid",
      station_id: "station-prep",
      name: "Service Hours",
      sort_order: 2,
      ...DEFAULT_SECTION_TIMING,
    },
    {
      id: "section-prep-closing",
      station_id: "station-prep",
      name: "End of Day",
      sort_order: 3,
      time: "22:00",
      recurrence: "daily_once",
      interval_minutes: null,
      due_window_minutes: 90,
    },
    {
      id: "section-dish-closing",
      station_id: "station-dish",
      name: "End of Day",
      sort_order: 1,
      time: "22:00",
      recurrence: "daily_once",
      interval_minutes: null,
      due_window_minutes: 90,
    },
    {
      id: "section-storage-opening",
      station_id: "station-storage",
      name: "Pre-Service",
      sort_order: 1,
      time: "06:00",
      recurrence: "daily_once",
      interval_minutes: null,
      due_window_minutes: 60,
    },
    {
      id: "section-storage-temp",
      station_id: "station-storage",
      name: "Temperature Monitoring",
      sort_order: 2,
      recurrence: "interval",
      interval_minutes: 120,
      due_window_minutes: 30,
    },
    {
      id: "section-storage-closing",
      station_id: "station-storage",
      name: "End of Day",
      sort_order: 3,
      time: "22:00",
      recurrence: "daily_once",
      interval_minutes: null,
      due_window_minutes: 90,
    },
  ],
  tasks: [
    {
      id: "task-1",
      station_id: "station-kitchen",
      section_id: "section-kitchen-opening",
      title: "Check walk-in fridge temperature",
      description: "Record temp — must be ≤ 41°F",
      timing_notes: "",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: "user-eduardo",
      sort_order: 1,
    },
    {
      id: "task-2",
      station_id: "station-storage",
      section_id: "section-storage-opening",
      title: "Check all freezer temperatures",
      description: "Record temp — must be ≤ 0°F",
      timing_notes: "",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: null,
      sort_order: 2,
    },
    {
      id: "task-3",
      station_id: "station-prep",
      section_id: "section-prep-pre-open",
      title: "Set up handwash stations",
      description: "Soap, paper towels, and warm running water at each station",
      timing_notes: "Verify again at open",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: "user-eduardo",
      sort_order: 3,
    },
    {
      id: "task-4",
      station_id: "station-kitchen",
      section_id: "section-kitchen-mid",
      title: "Gloves — no bare hand contact",
      description: "Verify all line cooks using gloves for ready-to-eat food",
      timing_notes: "",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: "user-eduardo",
      sort_order: 4,
    },
    {
      id: "task-5",
      station_id: "station-prep",
      section_id: "section-prep-mid",
      title: "Gloves — no bare hand contact",
      description: "Verify prep staff using gloves for ready-to-eat food",
      timing_notes: "",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: null,
      sort_order: 5,
    },
    {
      id: "task-6",
      station_id: "station-kitchen",
      section_id: "section-kitchen-temp",
      title: "Monitor hot-holding temps",
      description: "Check every 2 hours — must be ≥ 135°F",
      timing_notes: "Every 2 hours during service",
      recurrence: "interval",
      interval_minutes: 120,
      assigned_user_id: null,
      sort_order: 6,
    },
    {
      id: "task-7",
      station_id: "station-storage",
      section_id: "section-storage-temp",
      title: "Monitor cold-holding temps",
      description: "Check every 2 hours — must be ≤ 41°F",
      timing_notes: "Every 2 hours during service",
      recurrence: "interval",
      interval_minutes: 120,
      assigned_user_id: null,
      sort_order: 7,
    },
    {
      id: "task-8",
      station_id: "station-kitchen",
      section_id: "section-kitchen-closing",
      title: "Sanitize all food-contact surfaces",
      description: "Wipe down prep tables, cutting boards, and line surfaces",
      timing_notes: "",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: null,
      sort_order: 8,
    },
    {
      id: "task-9",
      station_id: "station-dish",
      section_id: "section-dish-closing",
      title: "Sanitize dish area surfaces",
      description: "Clean and sanitize sinks, racks, and surrounding areas",
      timing_notes: "",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: "user-eduardo",
      sort_order: 9,
    },
    {
      id: "task-10",
      station_id: "station-prep",
      section_id: "section-prep-closing",
      title: "Label and store all food",
      description: "Date-label all prep items and store at proper temps",
      timing_notes: "",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: null,
      sort_order: 10,
    },
    {
      id: "task-11",
      station_id: "station-storage",
      section_id: "section-storage-closing",
      title: "Label and store all food",
      description: "Ensure all stored items are labeled with date and contents",
      timing_notes: "",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: null,
      sort_order: 11,
    },
    {
      id: "task-12",
      station_id: "station-storage",
      section_id: "section-storage-closing",
      title: "Remove garbage",
      description: "Empty all trash bins and take to dumpster",
      timing_notes: "",
      recurrence: "daily_once",
      interval_minutes: null,
      assigned_user_id: null,
      sort_order: 12,
    },
  ],
  completions: [],
  mapZones: getDefaultMapZoneLabels(),
  mapLayout: getDefaultMapLayout(),
};
